### ISSUE TITLE
Integrate images on Tweets

### ISSUE THREAD

**Issue by viniciuskneves** [viniciuskneves/berlin_en_news#5]
Every article includes an image. It should be part of the tweet as well.

**Comment by leonardopavanrocha** [comment]
Hey @viniciuskneves! Really nice project. Could I take this one?

**Comment by viniciuskneves** [comment]
Hey @leonardopavanrocha thank you =]

Yep! I haven't set any code guidelines or so for now. Neither contribution guidelines. Feel free to follow your heart =]

**Comment by viniciuskneves** [comment]
Just as references:
- https://developer.twitter.com/en/docs/media/upload-media/overview
- https://developer.twitter.com/en/docs/tweets/post-and-engage/api-reference/post-statuses-update

**Comment by leonardopavanrocha** [comment]
Hey @viniciuskneves! I was checking the API documentation and perhaps using [Twitter Cards](https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/summary-card-with-large-image) would be an interesting idea. This option lets us post images as URLs instead of having to upload the image file to the API. What are your opinions on this topic?
